on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: ls -lah
      - run: echo "Building the project..." 
      - use: actions/checkout@v6
      - run: echo "Building the project... (not yet)" 