on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: ls -lah
      - run: echo "Building the project..." 
      - uses: actions/checkout@v6
      - run: npm run build
      - uses: cypress-io/github-action@v7
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Running tests..." 
      - run: echo "Tests passed! (not yet)"