on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building the project..." 
      - uses: actions/checkout@v6
      - run: ls -lah
      - run: npm ci
      - run: npm run build
      - name: Save cache
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            .next
            /home/runner/.cache/Cypress
          key: ${{ runner.obs}} -node-${{ hashFiles('**/package-lock.json') }}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache/restore@v5
        with:
          path: |
            node_modules
            .next
            /home/runner/.cache/Cypress
          key: ${{ runner.obs}} -node-${{ hashFiles('**/package-lock.json') }}
      - run: echo "Running tests..." 
      - name: Cypress e2e chrome
        uses: cypress-io/github-action@v7
        with:
          browser: chrome
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 60
      - run: echo "Running Cypress e2e test on chrome with GitHub Actions..."
      - name: Cypress e2e edge
        uses: cypress-io/github-action@v7
        with:
          browser: edge     
          start: npm start              
          wait-on: "http://localhost:3000" 
          wait-on-timeout: 60
          